# Site settings
title: blog.madewithlove.be
email: blog@madewithlove.be
description: >
  Yo yo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.madewithlove.be" # the base hostname & protocol for your site
twitter_username: madewithlove
github_username:  madewithlove

# Build settings
markdown: kramdown
permalink: "post/:title"

sass:
  sass_dir: _sass
  style: :compressed