# Site settings
title: "blog :: madewithlove"
email: blog@madewithlove.be
description: >
  articles by the madewithlove team
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.madewithlove.be" # the base hostname & protocol for your site
twitter_username: madewithlove
github_username:  madewithlove

# Build settings
markdown: kramdown
highlighter: pygments
permalink: "post/:title"

sass:
  sass_dir: _sass
  style: :compressed